version: 2
updates:
  # Enable updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" # Check for updates every week
    ignore:
      - dependency-name: "zone.js" # Example: ignore specific dependency updates
        update-types: ["version-update:semver-major"] # Ignore major version updates
    labels:
      - "dependencies"
      - "angular"

  # Enable updates for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily" # Check for updates daily
    labels:
      - "dependencies"
      - "actions"

groups:
  angular-dependencies:
    patterns:
      - "@angular/*" # Group all Angular-related dependencies
    labels:
      - "angular-group"

registries:
  npm-registry:
    type: "npm-registry"
    url: "https://registry.npmjs.org/"
